This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./transfermodule.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file transfermodule.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file transfermodule.acr....done (6 lines written, 0 warnings).
Output written in transfermodule.acr.
Transcript written in transfermodule.alg.
